[project]
name = "movie-watch-list-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.4"
dependencies = [
    "flask>=3.1.1",
    "jsonify>=0.5",
    "pytest>=8.4.1",
]
